= JSON Web Token validator policy

== Phase

|===
|onRequest |onResponse

| X
|
|===

== Description

You can use the `jwt` policy to validate the token signature and expiration date before sending the API call to the target backend.

Some authorization servers use OAuth2 protocol to provide access tokens. These access token can be in JWS/JWT format. For the RFC standards, see:

- JWS (JSON Web Signature) standard RFC: https://tools.ietf.org/html/rfc7515

- JWT (JSON Web Token) standard RFC: (https://tools.ietf.org/html/rfc7519

=== JWT

A JWT is composed of three parts: a header, a payload and a signature.
You can see some examples here: http://jwt.io.

- The header contains attributes indicating the algorithm used to sign the token.

- The payload contains some information inserted by the AS (Authorization Server), such as the expiration date and UID of the user.

Both the header and payload are encoded with Base64, so anyone can read the content.

- The third and last part is the signature (for more details, see the RFC).

== Configuration

|===
|Property |Required |Description |Type |Default

|publicKeyResolver|X|Used to resolve the public key needed to validate the signature|enum|GIVEN_KEY
|resolverParameter||Needed if you use the `GATEWAY_KEYS` or `GIVEN_ISSUER` resolver (EL support)|string|
|useSystemProxy||Select this option if you want use system proxy (only useful when resolver is `JWKS_URL`)|boolean|false
|extractClaims||Select this option if you want to extract claims into the request context|boolean|false
|===


To validate the token signature, the policy needs to use the associated Authorization Servers public key.

The policy prompts you to choose between three (`GIVEN_KEY`, `GIVEN_ISSUER`, `GATEWAY_ISSUER`) methods to retrieve the required public key.

 - `GIVEN_KEY` -- You provide the key (in `ssh-rsa`, `pem`, `crt` or `public-key` format)
 - `GIVEN_ISSUER` -- If you want to filter on several authorization servers then you only need to specify the issuer name; the gateway will only accept JWTs with a permitted issuer attribute. If `GATEWAY_KEYS` is set, the issuer is also used to retrieve the public key from the `gravitee.yml` file.
 - `GATEWAY_KEYS` -- You can set some public keys in the APIM Gateway `gravitee.yml` file

[source, yml]
----
policy:
  jwt:
    issuer:
      my.authorizaztion.server:
        default: ssh-rsa myValidationKey anEmail@domain.com
        kid-2016: ssh-rsa myCurrentValidationKey anEmail@domain.com
----

The policy will inspect the JWT:

** header to extract the key id (`kid` attribute) of the public key. If no key id is found then it is set to `default`.

** claims (payload) to extract the issuer (`iss` attribute)

Using these two values, the gateway can retrieve the corresponding public key.


== Attributes

|===
|Name |Description

.^|jwt.token
|JWT token extracted from the ```Authorization``` HTTP header

.^|jwt.claims
|A map of claims registered in the JWT token body, used for extracting data from it. Only if `extractClaims` is enabled in the policy configuration.

|===

== Example

Given the following JWT claims (payload):

[source, json]
----
{
  "iss": "Gravitee.io AM"
  "sub": "1234567890",
  "name": "John Doe",
  "admin": true
}
----

You can extract the issuer from JWT using the following Expression Language statement:

[source]
----
{#context.attributes['jwt.claims']['iss']}
----

== Errors

=== HTTP status code

|===
|Code |Message

| ```401```
| Bad token format, content, signature, expired token or any other issue preventing the policy from validating the token

|===

You can use the response template feature to override the default response provided by the policy. These templates must be defined at the API level (see the API Console *Response Templates*
option in the API *Proxy* menu).

The error keys sent by the policy are as follows:

[cols="2*", options="header"]
|===
^|Key
^|Parameters

.^|JWT_MISSING_TOKEN
^.^|-

.^|JWT_INVALID_TOKEN
^.^|-

|===

== Contributors

You can contribute comments using this GitHub issue link: https://github.com/gravitee-io/issues/issues/46
